services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: druido
      POSTGRES_PASSWORD: druido
      POSTGRES_DB: druido
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
